### ISSUE TITLE
Unable to add Attachment to the email message

### ISSUE THREAD

**Issue by tinku-borah** [datawookie/emayili#87]
Hi,

I used this package about 1 month back and I managed to add an attachment successfull in the email message but the same code doesn't work anymore.  It works perfectly when I don't add an attachment. The below code works

email <- envelope() %>%
      from(from_email) %>%
      to(to_email)%>%
      text("Please read the attached documents carefully. .\n Let us know") %>%
      text("Donot reply to this email. .\n") %>%
      subject("This is a plain text message!")

while the below code doesn't work :

email <- envelope() %>%
      from(from_email) %>%
      to(to_email)%>%
      text("Please read the attached documents carefully. .\n Let us know") %>%
      text("Donot reply to this email. .\n") %>%
      subject("This is a plain text message!") %>%
   attachment(path = "D:/sendemail/rmd_attachment/a.txt")

It gives the below error
Error: Request failed after 5 attempts
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning messages:
1: In f(...) : restarting interrupted promise evaluation
2: In f(...) : restarting interrupted promise evaluation
3: In f(...) : restarting interrupted promise evaluation
4: In f(...) :
 Error: Request failed after 5 attempts
Run `rlang::last_error()` to see where the error occurred.

**Comment by datawookie** [comment]
Hi @tinku-borah, thank you for bringing this to my attention! Indeed a regression had been introduced into how multi-part messages are compiled. I believe that I have fixed the issue. Would you mind testing for me, please?

Install `{emayili}` directly from GitHub as follows:

```R
remotes::install_github("datawookie/emayili", "v0.6.3")
```

Thanks, Andrew.

**Comment by tinku-borah** [comment]
Hi,
The issue still persists and now the existing functionality doesn't work too :(

    smtp <- server(
      host = "smtp.gmail.com",
      port = 465,
      username = "xxxxxxxxxxxxxxx",
      password = "xxxxxxxxxxxx"
    )
    
    
   
    email <- envelope() %>%
      from("xxxxxxxxxxxxxxxxxxxxxxxxxx") %>%
      to("xxxxxxxxxxxxxxxxxxxxxxxxxxx") %>%
      text("Please read the attached documents carefully. .\n Let us know") %>%
      text("Donot reply to this email. .\n") %>%
      subject("This is a plain text message!")
     # attachment("junk-report.docx")
     # attachment("D:/sendemail/main.R")
    
    smtp(email, verbose = FALSE)


Error:
Error: Request failed after 5 attempts
Run `rlang::last_error()` to see where the error occurred.

**Comment by tinku-borah** [comment]
Hi @datawookie ,

The updated code works. My port was incorrect and hence it had issues. Now I updated it
port = 587,
and works perectly. 
Thanks for fixing this. :)
